# Generated by Django 5.0.14 on 2026-07-22 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='anon_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Anonim ID'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Hodisa nomi'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='properties',
            field=models.JSONField(blank=True, default=dict, verbose_name='Xususiyatlar'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
