# Generated by Django 5.0.14 on 2026-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_price_drop',
            field=models.BooleanField(default=True),
        ),
    ]
