# Generated by Django 5.0.14 on 2026-07-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_telegram_chat_id_telegramlinkcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramlinkcode',
            options={'verbose_name': "Telegram bog'lash kodi", 'verbose_name_plural': "Telegram bog'lash kodlari"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'verbose_name': 'Tasdiqlash kodi', 'verbose_name_plural': 'Tasdiqlash kodlari'},
        ),
    ]
