# Generated by Django 5.0.14 on 2026-07-22 20:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramlinkcode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlinkcode',
            name='code',
            field=models.CharField(max_length=12, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='telegramlinkcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='telegramlinkcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='telegramlinkcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti"),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_passport',
            field=models.BooleanField(default=False, verbose_name='Pasport mavjud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_city',
            field=models.CharField(default='Tashkent', max_length=50, verbose_name='Yashash shahri'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Oylik daromad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_daily',
            field=models.BooleanField(default=True, verbose_name='Kunlik eslatma'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_price_drop',
            field=models.BooleanField(default=True, verbose_name='Narx pasayishi haqida xabar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_streak',
            field=models.BooleanField(default=True, verbose_name='Streak ogohlantirishi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_weekly',
            field=models.BooleanField(default=True, verbose_name='Haftalik hisobot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998901234567 formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Telegram chat ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='travel_style',
            field=models.CharField(choices=[('econom', 'Econom'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='standard', max_length=10, verbose_name='Sayohat uslubi'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar soni'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('password_reset', 'Parolni tiklash')], max_length=20, verbose_name='Maqsad'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
