# Generated by Django 5.0.14 on 2026-07-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_entries', to='trips.trip')),
            ],
            options={
                'verbose_name': "Jamg'arish yozuvi",
                'verbose_name_plural': "Jamg'arish yozuvlari",
                'ordering': ['-date'],
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
