# Generated by Django 5.0.14 on 2026-07-22 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_backfill_saving_entry_user'),
        ('trips', '0003_alter_budgetbreakdown_accommodation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='savingentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='savingentry',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='savingentry',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='savingentry',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_entries', to='trips.trip', verbose_name='Sayohat'),
        ),
        migrations.AlterField(
            model_name='savingentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saving_entries', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
