# Generated by Django 5.0.14 on 2026-07-23 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64, verbose_name='Tool nomi')),
                ('arguments', models.JSONField(default=dict, verbose_name='Parametrlar')),
                ('result', models.JSONField(default=dict, verbose_name='Natija')),
                ('success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_agent_logs', to=settings.AUTH_USER_MODEL, verbose_name='Bajardi')),
            ],
            options={
                'verbose_name': 'Agent amali',
                'verbose_name_plural': 'Agent amallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
