# Generated by Django 5.0.14 on 2026-07-20 19:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('visa_type', models.CharField(choices=[('free', 'Vizasiz'), ('on_arrival', 'Chegarada beriladi'), ('evisa', 'Elektron viza'), ('embassy', 'Elchixona orqali')], max_length=20)),
                ('visa_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('visa_note_uz', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_uz', models.CharField(max_length=100)),
                ('city_en', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('description_uz', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.country')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['city_uz'],
            },
        ),
        migrations.CreateModel(
            name='PriceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('flight_return_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hotel_night_econom', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hotel_night_standard', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hotel_night_comfort', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_day_econom', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_day_standard', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_day_comfort', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transport_day_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activity_day_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence', models.CharField(choices=[('high', 'Yuqori'), ('medium', "O'rtacha"), ('low', 'Past')], default='medium', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_references', to='destinations.destination')),
            ],
            options={
                'verbose_name': "Narx ma'lumotnomasi",
                'verbose_name_plural': "Narx ma'lumotnomalari",
                'ordering': ['destination', 'month'],
                'unique_together': {('destination', 'month')},
            },
        ),
    ]
