# Generated by Django 5.0.14 on 2026-07-22 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nomi (inglizcha)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name="Nomi (o'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='country',
            name='visa_cost_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Viza narxi (USD)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='visa_note_uz',
            field=models.TextField(blank=True, verbose_name='Viza haqida izoh'),
        ),
        migrations.AlterField(
            model_name='country',
            name='visa_type',
            field=models.CharField(choices=[('free', 'Vizasiz'), ('on_arrival', 'Chegarada beriladi'), ('evisa', 'Elektron viza'), ('embassy', 'Elchixona orqali')], max_length=20, verbose_name='Viza turi'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city_en',
            field=models.CharField(max_length=100, verbose_name='Shahar (inglizcha)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city_uz',
            field=models.CharField(max_length=100, verbose_name="Shahar (o'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.country', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Rasm havolasi'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Mashhur'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='activity_day_usd',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Faoliyat/kun (USD)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='confidence',
            field=models.CharField(choices=[('high', 'Yuqori'), ('medium', "O'rtacha"), ('low', 'Past')], default='medium', max_length=10, verbose_name='Ishonchlilik'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_references', to='destinations.destination', verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='flight_return_usd',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Chipta narxi (borish-kelish, USD)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='food_day_comfort',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ovqat/kun (comfort)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='food_day_econom',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ovqat/kun (econom)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='food_day_standard',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ovqat/kun (standard)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='hotel_night_comfort',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Mehmonxona/kecha (comfort)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='hotel_night_econom',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Mehmonxona/kecha (econom)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='hotel_night_standard',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Mehmonxona/kecha (standard)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='transport_day_usd',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Transport/kun (USD)'),
        ),
        migrations.AlterField(
            model_name='pricereference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
