# Generated by Django 5.0.14 on 2026-07-20 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField()),
                ('travelers_count', models.PositiveIntegerField(default=1)),
                ('style', models.CharField(choices=[('econom', 'Econom'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='standard', max_length=10)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planning', 'Rejalashtirilmoqda'), ('saving', "Jamg'arilmoqda"), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='planning', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='destinations.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sayohat',
                'verbose_name_plural': 'Sayohatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='trips.trip')),
            ],
            options={
                'verbose_name': "Byudjet bo'linishi",
                'verbose_name_plural': "Byudjet bo'linishlari",
            },
        ),
    ]
