# Generated by Django 5.0.14 on 2026-07-22 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_country_code_alter_country_is_active_and_more'),
        ('trips', '0002_tripmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='accommodation',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Turar joy'),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='activities',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Faoliyatlar'),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='flight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chipta'),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='food',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ovqat'),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='insurance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Sug'urta"),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='reserve',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zaxira'),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='transport',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transport'),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='trips.trip', verbose_name='Sayohat'),
        ),
        migrations.AlterField(
            model_name='budgetbreakdown',
            name='visa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Viza'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Byudjet (maks)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Byudjet (min)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='destinations.destination', verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='Davomiyligi (kun)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planning', 'Rejalashtirilmoqda'), ('saving', "Jamg'arilmoqda"), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='planning', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='style',
            field=models.CharField(choices=[('econom', 'Econom'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='standard', max_length=10, verbose_name='Uslub'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maqsad summasi'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelers_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Sayohatchilar soni'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='tripmember',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='tripmember',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trips.trip', verbose_name='Sayohat'),
        ),
        migrations.AlterField(
            model_name='tripmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
